Repository Next-Room/NextRoom-Android, pull requests merged in 2023-11, with the labels that each got.

#32 메모화면 풀스크린 적용
  presentation/src/main/java/com/nextroom/nextroom/presentation/base/BaseFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/extension/View.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/adminmain/AdminMainFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/hint/HintFragment.kt
  presentation/src/main/res/layout/fragment_memo.xml
Labels: bug, refactor

#37 결제 승인 처리 구현
  app/build.gradle.kts
  app/src/main/java/com/nextroom/nextroom/di/BillingModule.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/billing/BillingEvent.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/billing/BillingViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/purchase/PurchaseEvent.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/purchase/PurchaseFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/purchase/PurchaseViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/util/BillingClientLifecycle.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#35 토큰 방식으로 변경
  app/src/main/java/com/nextroom/nextroom/di/RepositoryModule.kt
  data/src/main/java/com/nextroom/nextroom/data/datasource/AuthDataSource.kt
  data/src/main/java/com/nextroom/nextroom/data/datasource/SubscriptionDataSource.kt
  data/src/main/java/com/nextroom/nextroom/data/datasource/ThemeRemoteDataSource.kt
  data/src/main/java/com/nextroom/nextroom/data/datasource/TokenDataSource.kt
  data/src/main/java/com/nextroom/nextroom/data/di/NetworkModule.kt
  data/src/main/java/com/nextroom/nextroom/data/model/TokenDto.kt
  data/src/main/java/com/nextroom/nextroom/data/network/ApiService.kt
  data/src/main/java/com/nextroom/nextroom/data/network/AuthAuthenticator.kt
  data/src/main/java/com/nextroom/nextroom/data/network/AuthInterceptor.kt
  data/src/main/java/com/nextroom/nextroom/data/network/response/BaseResponse.kt
  data/src/main/java/com/nextroom/nextroom/data/network/response/ListDto.kt
  data/src/main/java/com/nextroom/nextroom/data/network/response/LoginDto.kt
  data/src/main/java/com/nextroom/nextroom/data/network/response/UserSubscriptionStatusResponse.kt
  data/src/main/java/com/nextroom/nextroom/data/repository/AdminRepositoryImpl.kt
  data/src/main/java/com/nextroom/nextroom/data/repository/ThemeRepositoryImpl.kt
  domain/src/main/java/com/nextroom/nextroom/domain/model/Subscribe.kt
  domain/src/main/java/com/nextroom/nextroom/domain/request/TokenRefreshRequest.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/adminmain/AdminMainState.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/adminmain/AdminMainViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feature, refactor

#41 카운트다운 화면 이탈 시 동작 수정 + 기타 작업
  data/src/main/java/com/nextroom/nextroom/data/repository/TimerRepositoryImpl.kt
  domain/src/main/java/com/nextroom/nextroom/domain/model/TimerState.kt
  domain/src/main/java/com/nextroom/nextroom/domain/repository/TimerRepository.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/base/BaseViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/model/Hint.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/counter/CounterFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/counter/CounterViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/hint/HintEvent.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/hint/HintFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/hint/HintState.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/hint/HintViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameEvent.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameScreenState.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/memo/MemoFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/memo/PainterViewModel.kt
  presentation/src/main/res/navigation/nav_graph.xml
Labels: bug, feature, refactor

#44 통계 기능 구현
  app/src/main/java/com/nextroom/nextroom/di/RepositoryModule.kt
  commonutil/src/main/java/com/mangbaam/commonutil/DateTimeUtil.kt
  data/src/main/java/com/nextroom/nextroom/data/datasource/StatisticsDataSource.kt
  data/src/main/java/com/nextroom/nextroom/data/db/NextRoomDatabase.kt
  data/src/main/java/com/nextroom/nextroom/data/db/StatisticsDao.kt
  data/src/main/java/com/nextroom/nextroom/data/di/LocalDataModule.kt
  data/src/main/java/com/nextroom/nextroom/data/model/StatisticsEntity.kt
  data/src/main/java/com/nextroom/nextroom/data/network/ApiService.kt
  data/src/main/java/com/nextroom/nextroom/data/network/request/StatisticsRequest.kt
  data/src/main/java/com/nextroom/nextroom/data/repository/StatisticsRepositoryImpl.kt
  domain/src/main/java/com/nextroom/nextroom/domain/model/statistics/GameStats.kt
  domain/src/main/java/com/nextroom/nextroom/domain/model/statistics/HintStats.kt
  domain/src/main/java/com/nextroom/nextroom/domain/repository/StatisticsRepository.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/adminmain/AdminMainFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/hint/HintViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/purchase/PurchaseViewModel.kt
Labels: feature
