Repository Next-Room/NextRoom-Android, pull requests merged in 2023-10, with the labels that each got.

#20 #19 fix: 로그아웃 버튼 동작 수정
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/MainEvent.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameFragment.kt
Labels: bug

#25 #23 feat: 구독 기능 초기 세팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextroom/nextroom/di/RepositoryModule.kt
  data/src/main/java/com/nextroom/nextroom/data/datasource/BillingDataSource.kt
  data/src/main/java/com/nextroom/nextroom/data/repository/BillingRepositoryImpl.kt
  domain/src/main/java/com/nextroom/nextroom/domain/repository/BillingRepository.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/BillingViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/Constants.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/util/BillingClientLifecycle.kt
Labels: feature

#26 #18 feat: 온보딩 페이지 구현
  app/src/main/java/com/nextroom/nextroom/di/RepositoryModule.kt
  data/src/main/java/com/nextroom/nextroom/data/datasource/SettingDataSource.kt
  data/src/main/java/com/nextroom/nextroom/data/db/AppSettings.kt
  data/src/main/java/com/nextroom/nextroom/data/repository/DataStoreRepositoryImpl.kt
  domain/src/main/java/com/nextroom/nextroom/domain/repository/DataStoreRepository.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/MainEvent.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/MainViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/login/LoginEvent.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/login/LoginFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/onboarding/OnboardingFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/verity/VerifyFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/verity/VerifyViewModel.kt
  presentation/src/main/res/drawable/bg_onboarding.png
  presentation/src/main/res/layout/fragment_admin_code.xml
  presentation/src/main/res/layout/fragment_login.xml
  presentation/src/main/res/layout/fragment_onboarding.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#28 BaseFragment 리팩터링
  presentation/src/main/java/com/nextroom/nextroom/presentation/base/BaseFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/extension/Activity.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/extension/Fragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/adminmain/AdminMainFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/counter/CounterFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/hint/HintFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/login/LoginFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/memo/MemoFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/onboarding/OnboardingFragment.kt
  presentation/src/main/java/com/nextroom/nextroom/presentation/ui/verity/VerifyFragment.kt
Labels: refactor
